### ISSUE TITLE
Semester Thesis + SoM presentation wrong?

### ISSUE THREAD

**Issue by philipoe** [ethz-asl/asl-student-templates#23]
Under the topic "Final Presentation", the wiki mentions "Semester/Bachelor Project with integrated SoM: 22 minutes presentation, 8 minutes questions / discussion". However, doing a Semester project _together_ with an _integrated_ SoM should not even be possible because one is part of the Bachelor curriculum and one is part of the Master's curriculum.

@pfankhauser Should this be changed?

**Comment by pfankhauser** [comment]
Yes you are absolutely right. Feel free to adapt it to be more accurate, thanks!

**Comment by philipoe** [comment]
Done, closing this issue.
